### ISSUE TITLE
Two sliders at same page. when I show hidden one it looks not good

### ISSUE THREAD

**Issue by mus-int** [Wlada/vue-carousel-3d#10]
Hi
I'm using two sliders at same page.
one of them is hidden.
I have two buttons to toggle show between them. and every thing works well.
but when I resize the window and try to show hidden slider. the slider is shown but not look good and not centered on the screen.
after I show the hidden slider, if I resize the window the slider will be fine again.
this is an example of the [issue](https://jsfiddle.net/uphowemj/3/).

so the problem is:
when I resize the window and try to show the hidden slider.

**Comment by Wlada** [comment]
This is normal because when you are resizing hidden carousel his wrapper element has width 0 and height 0. Wrapper width and height is important because carousel slide width can't be bigger than wrapper width. 
Right now I'm pretty busy and can't help immediately, but I will take a look just to get some free time.

**Comment by Wlada** [comment]
http://stackoverflow.com/questions/42555215/two-sliders-at-same-page-when-i-show-hidden-one-it-looks-not-good
